// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "GhostGuide",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "GhostGuide",
            targets: ["AppModule"],
            teamIdentifier: "M9NL4PJ9AL",
            displayVersion: "1.0",
            bundleVersion: "1",
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .locationAlwaysAndWhenInUse(purposeString: "GhostGuide uses your location in the background to detect invisible tripwires around historical monuments."),
                .locationWhenInUse(purposeString: "GhostGuide needs to see where you are to find nearby stories.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)